steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/gcloud-sops', '.']
- # Verify sops has been built correctly
  name: 'gcr.io/$PROJECT_ID/gcloud-sops'
  args: ['-v']
images: ['gcr.io/$PROJECT_ID/gcloud-sops']
