steps:
  - name: "gcr.io/$PROJECT_ID/helm"
    args:
      [
        "--environment",
        "environment-name",
        "--file",
        "/path/to/state/file",
        "sync",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=cluster-zone"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-name"
tags: ["cloud-builders-community"]
